name: 'Setup Ubuntu'
description: 'Set up Ubuntu for installing TSWoW'
runs:
  using: "composite"
  steps:
    - name: Select node version
      uses: actions/setup-node@v3
      with:
        node-version: 18.12.1
    - name: Install deps
      shell: bash
      run: |
        apt-get update
        apt-get install git clang cmake make gcc g++ libmysqlclient-dev libssl-dev libbz2-dev libreadline-dev libncurses-dev libboost-all-dev mysql-server p7zip
        update-alternatives --install /usr/bin/cc cc /usr/bin/clang 100
        update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang 100